// FanCtrl3 enclosure - one parametric file for both variants.
//
//   openscad -D 'variant="pro"'  -D 'part="base"' -o pro-base.stl  FanCtrl3-enclosure.scad
//   openscad -D 'variant="lite"' -D 'part="lid"'  -o lite-lid.stl  FanCtrl3-enclosure.scad
//
// variant: "pro" (custom PCB 90 x 60 mm) or "lite" (PC-3 perfboard 72 x 47 mm)
// part:    "base", "lid", "assembly" (preview with the board), "collisions" (the
//          intersection of the enclosure and the component bodies - must be empty)
//
// Printing: PETG, no supports. The base prints bottom down, the lid top down (the
// lid STL is already flipped). 2 mm walls.
// Board: 4 x M3x8 screwed from above into the standoffs. Lid: 4 x M3x8 into bosses
// in the corners, outside the board outline. RF8-2A rubber feet sit in shallow
// pockets in the floor.
//
// Board coordinates as in KiCad / design_lite.py: x to the right, y down from the
// top edge, in mm. b() converts them to OpenSCAD coordinates (y up).

variant = "pro";
part = "assembly";

// Lite component positions - generated by tools/gen_lite.py from design_lite.py
include <FanCtrl3-lite-geometry.scad>

$fn = 48;

// --- common --------------------------------------------------------------------
wall = 2.0;           // side walls
floor_t = 2.0;        // floor
lid_t = 2.0;          // lid plate
gap = 0.8;            // clearance between board edge and wall
strip = 7.0;          // extra room above and below the board for the lid bosses
outer_r = 3.0;        // outer corner radius
pcb_t = 1.6;
standoff_h = 5.0;     // standoff height (room for solder joints and wires below)
standoff_d = 7.0;
pilot_d = 2.6;        // pilot hole for an M3 screw cutting into PETG
pilot_depth = 6.5;    // M3x8: 1.6 mm board + 6.4 mm into the standoff
boss_d = 7.0;         // lid screw bosses
lid_hole_d = 3.4;
lip_h = 1.5;          // lid lip that drops into the base
lip_t = 1.2;
lip_gap = 0.3;
foot_d = 9.0;         // RF8-2A: 8 mm, 2 mm thick -> sticks out 1 mm
foot_depth = 1.0;
usb_w = 12;           // opening for the micro-USB plug including its overmould
usb_h = 8;
probe_d = 6;          // DS18B20 probe cable entry
fan_slot = [12, 9];   // lid opening above each fan header (plug is ~11 mm wide)
led_d = 5;
vent_w = 1.6;
vent_pitch = 3.6;
text_depth = 0.6;

// --- variants -------------------------------------------------------------------
pro = variant == "pro";
W = pro ? 90 : 72;
H = pro ? 60 : 47;
board_r = pro ? 3 : 0.5;
// lite: PC-3 mounting holes read off the distributor's product photo (3.0 mm from
// the edge, 3.5 mm diameter) - measure your board with calipers before printing
hole_inset = pro ? 3.5 : 3.0;
hole_d = pro ? 3.2 : 3.5;
top_clear = pro ? 14 : 19;              // board top to lid underside
// pro: from the KiCad board (FanCtrl3-Pro.kicad_pcb), lite: from the geometry file
usb_y = pro ? 21 : lite_usb_y;          // centre of the Pico micro-USB socket
usb_z = pro ? 2.3 : lite_usb_z;         // ... above the board top
fan_x = pro ? [12.81, 26.81, 40.81] : lite_fan_x;
fan_y = pro ? 55 : lite_fan_y;
probe_front = pro;                      // pro: probe enters at the front, lite: on the right
probe_pos = pro ? 76.54 : lite_probe_y; // x (front wall) or y (right wall)
probe_z = 4;                            // wire entry of the terminal above the board
led = pro ? [4.9, 26.8] : lite_led;
vent = pro ? [62, 4, 84, 19] : lite_vent;   // x0 y0 x1 y1

// --- derived dimensions ---------------------------------------------------------------
ix0 = -gap; ix1 = W + gap;
iy0 = -gap - strip; iy1 = H + gap + strip;
ox0 = ix0 - wall; ox1 = ix1 + wall;
oy0 = iy0 - wall; oy1 = iy1 + wall;
board_z = floor_t + standoff_h;          // board underside
top_z = board_z + pcb_t + top_clear;     // top of the walls = lid underside
holes = [[hole_inset, hole_inset], [W - hole_inset, hole_inset],
         [hole_inset, H - hole_inset], [W - hole_inset, H - hole_inset]];
bosses = [[ix0 + boss_d / 2, iy0 + boss_d / 2], [ix1 - boss_d / 2, iy0 + boss_d / 2],
          [ix0 + boss_d / 2, iy1 - boss_d / 2], [ix1 - boss_d / 2, iy1 - boss_d / 2]];

function b(x, y) = [x, H - y];

module rrect(x0, y0, x1, y1, r) {
    translate([x0, y0]) offset(r) offset(-r) square([x1 - x0, y1 - y0]);
}

module teardrop(d, len) {  // horizontal hole printable without supports, axis along Y
    rotate([90, 0, 0]) linear_extrude(len, center = true)
        union() { circle(d = d); rotate(45) square(d / 2); }
}

// --- base ---------------------------------------------------------------------
module base() {
    difference() {
        union() {
            difference() {
                linear_extrude(top_z) rrect(ox0, oy0, ox1, oy1, outer_r);
                translate([0, 0, floor_t])
                    linear_extrude(top_z) rrect(ix0, iy0, ix1, iy1, outer_r - wall);
            }
            for (p = bosses) translate(p) cylinder(d = boss_d, h = top_z);
            for (p = holes) translate(b(p[0], p[1])) cylinder(d = standoff_d, h = board_z);
        }
        for (p = bosses) translate([p[0], p[1], top_z - pilot_depth - 1])
            cylinder(d = pilot_d, h = pilot_depth + 2);
        for (p = holes) translate([each b(p[0], p[1]), board_z - pilot_depth])
            cylinder(d = pilot_d, h = pilot_depth + 1);
        // micro-USB in the left wall
        translate([ox0 - 1, H - usb_y - usb_w / 2, board_z + pcb_t + usb_z - usb_h / 2])
            cube([wall + gap + 2, usb_w, usb_h]);
        // probe cable entry
        if (probe_front)
            translate([probe_pos, oy0 + wall / 2, board_z + pcb_t + probe_z])
                teardrop(probe_d, wall + 2);
        else
            translate([ox1 - wall / 2, H - probe_pos, board_z + pcb_t + probe_z])
                rotate([0, 0, 90]) teardrop(probe_d, wall + 2);
        // foot pockets - under the lid bosses, away from the board screw holes
        for (p = bosses) translate([p[0], p[1], -1]) cylinder(d = foot_d, h = foot_depth + 1);
    }
}

// --- lid (in assembled position: plate from top_z up, lip down) ----------------
module lid() {
    difference() {
        union() {
            translate([0, 0, top_z]) linear_extrude(lid_t) rrect(ox0, oy0, ox1, oy1, outer_r);
            difference() {
                translate([0, 0, top_z - lip_h]) linear_extrude(lip_h + 0.01) difference() {
                    rrect(ix0 + lip_gap, iy0 + lip_gap, ix1 - lip_gap, iy1 - lip_gap, 1);
                    rrect(ix0 + lip_gap + lip_t, iy0 + lip_gap + lip_t,
                          ix1 - lip_gap - lip_t, iy1 - lip_gap - lip_t, 0.5);
                }
                for (p = bosses) translate([p[0], p[1], top_z - lip_h - 1])
                    cylinder(d = boss_d + 2 * lip_gap, h = lip_h + 2);
                // no lip above the USB plug
                translate([ix0 - 1, H - usb_y - usb_w / 2 - 1, top_z - lip_h - 1])
                    cube([lip_t + lip_gap + 2, usb_w + 2, lip_h + 2]);
            }
        }
        for (p = bosses) translate([p[0], p[1], top_z - 5]) cylinder(d = lid_hole_d, h = 10);
        for (x = fan_x) translate([each b(x, fan_y), top_z - 1])
            linear_extrude(lid_t + 2) rrect(-fan_slot[0] / 2, -fan_slot[1] / 2,
                                            fan_slot[0] / 2, fan_slot[1] / 2, 1.5);
        translate([each b(led[0], led[1]), top_z - 1]) cylinder(d = led_d, h = lid_t + 2);
        // vent slots above the boost converter
        for (x = [vent[0] : vent_pitch : vent[2] - vent_w])
            translate([x, H - vent[3], top_z - 1]) cube([vent_w, vent[3] - vent[1], lid_t + 2]);
        // engraved labels
        translate([0, 0, top_z + lid_t - text_depth]) linear_extrude(text_depth + 1) {
            translate(b(W / 2, fan_y - fan_slot[1] / 2 - 4))
                text(pro ? "FanCtrl3 Pro" : "FanCtrl3 Lite", size = 4, halign = "center",
                     valign = "center", font = "Liberation Sans:style=Bold");
            for (i = [0 : 2]) translate(b(fan_x[i], fan_y + fan_slot[1] / 2 + 3.5))
                text(str(i + 1), size = 3.5, halign = "center", valign = "center",
                     font = "Liberation Sans:style=Bold");
        }
    }
}

// --- component bodies (for the preview and the collision check) ---------------------------
module blk(x0, y0, x1, y1, z0, z1) {  // box in board coordinates
    translate([x0, H - y1, board_z + pcb_t + z0]) cube([x1 - x0, y1 - y0, z1 - z0]);
}
module cyl(x, y, d, z1) { translate([each b(x, y), board_z + pcb_t]) cylinder(d = d, h = z1); }

module components() {
    if (pro) {
        for (x = fan_x) blk(x - 5.1, fan_y - 3, x + 5.1, fan_y + 3, 0, 12);   // 4-pin fan headers
        blk(0.2, 21 - 10.5, 51.2, 21 + 10.5, 0, 2);          // Pico soldered flat on the board
        blk(-0.8, 21 - 4, 5, 21 + 4, 1, 3.6);                // micro-USB socket
        cyl(60, 50, 6.3, 12);                                // C6 100 uF
        blk(72, 51.4, 81.2, 59.2, 0, 8.5);                   // J4 probe terminal
        blk(68.5, 13, 73.5, 18, 0, 4);                       // L1 inductor
    } else {
        for (q = lite_boxes) blk(q[0], q[1], q[2], q[3], q[4], q[5]);
    }
}

module board() {
    translate([0, 0, board_z]) linear_extrude(pcb_t) difference() {
        rrect(0, 0, W, H, board_r);
        for (p = holes) translate(b(p[0], p[1])) circle(d = hole_d);
    }
}

if (part == "base") base();
else if (part == "lid") translate([0, 0, top_z + lid_t]) rotate([180, 0, 0]) lid();
else if (part == "collisions") intersection() { union() { base(); lid(); } components(); }
else {
    color("#e9ecef") base();
    color("#4dabf7", 0.55) translate([0, 0, 12]) lid();
    color("#2b8a3e") board();
    color("#fab005") components();
}
