M48
; DRILL file KiCad 10.0.6 date 2026-09-23T10:51:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-23T10:51:57+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X104.73Y-118.575
X104.73Y-123.425
T2
X101.7Y-118.275
X101.7Y-123.725
T3
X103.5Y-103.5
X103.5Y-156.5
X186.5Y-103.5
X186.5Y-156.5
M30
